# Generated by Django 4.1.3 on 2022-12-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfilled',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
