# Generated by Django 4.1.3 on 2022-12-29 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_order_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 14, 14, 52, 909489)),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
