# Generated by Django 4.1.3 on 2022-12-29 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_expiry_time_alter_order_fulfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 14, 21, 48, 776624, tzinfo=datetime.timezone.utc)),
        ),
    ]
