# Generated by Django 4.1.3 on 2022-12-30 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_order_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 16, 56, 13, 350466, tzinfo=datetime.timezone.utc)),
        ),
    ]
