# Generated by Django 4.1.3 on 2022-12-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_order_expiry_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='price',
            new_name='buy_price',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expiry_time',
        ),
        migrations.AddField(
            model_name='order',
            name='fulfilled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
